version: "3.9"

networks:
  todo_list_net:
    name: todo_list_net
    driver: bridge

services:
  todo_list_api:
    build:
      context: ./server/
      target: development
    image: todo_list_api
    container_name: todo_list_api
    ports:
      - "8080:8080"
      - "5005:5005"   # Remote debug
    environment:
      - SERVER_PORT=8080
    networks:
      - todo_list_net
