version: "3.9"

networks:
  gateway:
    name: todo-list-net
    driver: bridge

services:
  backend-dev:
    profiles: [ "dev" ]
    build:
      context: .
      target: development
    image: todo-list-api:dev
    container_name: tl-api-dev
    tty: true
    ports:
      - "8080:8080"
      - "5005:5005" # Remote debug
    networks:
      - gateway

  backend-test:
    profiles: [ "test" ]
    build:
      context: .
      target: test
    image: todo-list-api:test
    container_name: tl-api-test
    tty: true
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - gateway
